import JSZip from "jszip";

// Data pack + resource pack format 15 corresponds to Minecraft Java
// 1.20 - 1.20.1, matching STRUCTURE_DATA_VERSION in structure.ts.
const PACK_FORMAT = 15;

export function sanitizeResourceName(input: string): string {
  const cleaned = input
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9_.-]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return cleaned.length > 0 ? cleaned : "project";
}

export type DatapackStructure = { name: string; nbt: Buffer };

export type AssembleDatapackParams = {
  projectName: string;
  namespace: string;
  theme: string;
  structures: DatapackStructure[];
  blueprintTexturePng?: Uint8Array;
};

export async function assembleDatapackZip(params: AssembleDatapackParams): Promise<Buffer> {
  const { projectName, namespace, theme, structures, blueprintTexturePng } = params;
  const zip = new JSZip();

  const readme = `${projectName} -- Minecraft datapack + resource pack
Generated by the mod generator. Theme: ${theme}

INSTALL
1. Datapack (adds the custom structure + a build command):
   - Copy the "datapack" folder into: <your world save>/datapacks/
     (In-game: create/open a world, then Options > Open World Folder > datapacks)
   - Rename the copied folder if you like, then run "/reload" in-game.
   - Run one of the build functions below to place the structure at your
     location: "/function ${namespace}:${structures[0] ? sanitizeResourceName(structures[0].name) : "build"}"

${structures
  .map((s) => `   - /function ${namespace}:${sanitizeResourceName(s.name)}  (places "${s.name}")`)
  .join("\n")}

${
  blueprintTexturePng
    ? `2. Resource pack (reskins vanilla Paper items with your generated texture):
   - Copy the "resourcepack" folder into: %appdata%/.minecraft/resourcepacks/
     (macOS: ~/Library/Application Support/minecraft/resourcepacks/)
   - In-game: Options > Resource Packs, enable it.
   - Note: this replaces the appearance of ALL vanilla Paper items while
     active -- expected behavior for this personal creative-tool pack.
`
    : ""
}
Target version: Minecraft Java Edition 1.20 - 1.20.4 (pack_format ${PACK_FORMAT}).
Newer versions may show a "may not work" warning when loading the pack --
that's expected and safe to confirm through; Minecraft upgrades old data
automatically.
`;

  zip.file("README.txt", readme);

  const dp = zip.folder("datapack")!;
  dp.file(
    "pack.mcmeta",
    JSON.stringify(
      {
        pack: {
          pack_format: PACK_FORMAT,
          description: `${projectName} -- generated structures (${theme})`,
        },
      },
      null,
      2
    )
  );

  for (const structure of structures) {
    const safeName = sanitizeResourceName(structure.name);
    dp.file(`data/${namespace}/structure/${safeName}.nbt`, structure.nbt);
    dp.file(
      `data/${namespace}/function/${safeName}.mcfunction`,
      `# Places "${structure.name}" centered on your current position\nplace template ${namespace}:${safeName} ~ ~ ~\n`
    );
  }

  if (blueprintTexturePng) {
    const rp = zip.folder("resourcepack")!;
    rp.file(
      "pack.mcmeta",
      JSON.stringify(
        {
          pack: {
            pack_format: PACK_FORMAT,
            description: `${projectName} -- generated blueprint item texture`,
          },
        },
        null,
        2
      )
    );
    rp.file("assets/minecraft/textures/item/paper.png", blueprintTexturePng);
    rp.file(
      "assets/minecraft/models/item/paper.json",
      JSON.stringify(
        {
          parent: "minecraft:item/generated",
          textures: { layer0: "minecraft:item/paper" },
        },
        null,
        2
      )
    );
  }

  return zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });
}
